'use strict';
/**
 * The stylesheets and scripts the browser actually loads.
 *
 * This exists because public/backoffice/style.css was once truncated from 24 KB to
 * 815 bytes by a bad append and nothing noticed: every unit test passed, the server
 * started, the page returned 200, and the only symptom was that the back office
 * rendered as unstyled text. A file that is quietly emptied is invisible to every
 * other kind of test here, so it gets its own.
 *
 * The floors are deliberately well under current size — this is a truncation alarm,
 * not a budget. The markers are load-bearing selectors: if one disappears, either
 * the file was clobbered or the class was renamed without updating the HTML.
 */
const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');

const ASSETS = [
  { file: 'public/shared/theme.css',      min: 6000, markers: ['.tabs', '.btn', ':root'] },
  { file: 'public/backoffice/style.css',  min: 15000, markers: ['.pane', '.cards', '.no-grant', '.f .fh'] },
  { file: 'public/backoffice/login.css',  min: 1500, markers: ['.btn-o'] },
  { file: 'public/client/style.css',      min: 6000, markers: ['.issue', '.bidbox', '.bb-row', '.bb-otp', '.tabs.door'] },
  { file: 'public/shared/rules.css',      min: 1000, markers: ['.rules'] },
  // This one file is BOTH shells now — the desk at /backoffice and a branch at
  // /partner — so the markers cover the partner half too.
  { file: 'public/backoffice/app.js',     min: 40000, markers: ['function boot(', 'function applyGrants(',
                                                                 'function partnerPath(', 'function loadPartnerClients('] },
  { file: 'public/client/client.js',      min: 12000, markers: ['function boot(', 'function bidBox(',
                                                                 'function sendBranchCode(', 'function bidBase('] },
  { file: 'public/shared/rules.js',       min: 3000, markers: [] }
];

for (const a of ASSETS) {
  test(a.file + ' is present and not truncated', () => {
    const s = read(a.file);
    assert.ok(s.length >= a.min,
      a.file + ' is ' + s.length + ' bytes, under the ' + a.min + ' floor — truncated?');
    for (const m of a.markers) {
      assert.ok(s.includes(m), a.file + ' no longer contains ' + JSON.stringify(m));
    }
  });
}

test('every stylesheet has balanced braces', () => {
  for (const a of ASSETS.filter((x) => x.file.endsWith('.css'))) {
    const s = read(a.file);
    const open = (s.match(/{/g) || []).length;
    const close = (s.match(/}/g) || []).length;
    assert.equal(open, close, a.file + ' has ' + open + ' { and ' + close + ' }');
  }
});

/**
 * Every stylesheet and script the pages reference must exist on disk, resolved the
 * way the server actually mounts them (server.js). The client app is served from
 * '/', so its own '/style.css' is public/client/style.css — not public/style.css,
 * which is what makes this worth checking rather than eyeballing.
 */
const MOUNTS = [
  ['/shared/', 'public/shared/'],
  ['/backoffice/', 'public/backoffice/'],
  ['/', 'public/client/']            // catch-all, so it must come last
];

function resolveRef(url) {
  for (const [prefix, dir] of MOUNTS) {
    if (url.startsWith(prefix)) return dir + url.slice(prefix.length);
  }
  return null;
}

test('every asset each page links actually exists', () => {
  for (const page of ['public/backoffice/index.html', 'public/backoffice/login.html',
                      'public/backoffice/issue.html', 'public/client/index.html']) {
    const html = read(page);
    const refs = [];
    const re = /(?:href|src)="(\/[^"]+\.(?:css|js))"/g;
    let m;
    while ((m = re.exec(html))) refs.push(m[1]);
    assert.ok(refs.length, page + ' links no stylesheet or script at all');
    for (const r of refs) {
      if (r === '/config.js') continue;          // generated by the server, not a file
      const onDisk = resolveRef(r);
      assert.ok(onDisk, page + ' links ' + r + ', which no static mount serves');
      assert.ok(fs.existsSync(path.join(ROOT, onDisk)),
        page + ' links ' + r + ' -> ' + onDisk + ', which does not exist');
    }
  }
});

/**
 * A control bound to an element that does not exist.
 *
 * $('#x') returns null when #x is absent, and $('#x').addEventListener then throws —
 * except it is usually inside boot(), where one throw stops every binding after it.
 * Either way the control silently does nothing, the page looks fine, and nothing in
 * the console explains it. "Bid on this issue" shipped bound to #dashIssues, which
 * has never existed; the cards container is #issueCards.
 *
 * An id is legitimate if the page declares it, OR if the script builds it — plenty
 * of these are created and bound in the same breath.
 */
test('every addEventListener target exists in the page or is built by the script', () => {
  const pairs = [
    ['public/backoffice/app.js', 'public/backoffice/index.html'],
    ['public/client/client.js', 'public/client/index.html']
  ];
  for (const [js, html] of pairs) {
    const src = read(js);
    const page = read(html);
    const bound = new Set();
    src.replace(/\$\('#([A-Za-z0-9_-]+)'\)\.addEventListener/g, (m, id) => { bound.add(id); return m; });
    assert.ok(bound.size > 10, js + ': found suspiciously few bindings to check');

    for (const id of bound) {
      const inPage = new RegExp('id="' + id + '"').test(page);
      const built = new RegExp('id="' + id + '"').test(src) ||
                    new RegExp("id=\\\\'" + id + "\\\\'").test(src);
      assert.ok(inPage || built,
        js + ' binds #' + id + ', which neither the page declares nor the script creates');
    }
  }
});

/**
 * The issue master fitting on the screen.
 *
 * The row expander is a <tr> inside the same table as the rows, so a table wider
 * than the viewport drags the detail panel off the right edge with it — the floor,
 * the book, the document upload, all past the fold behind a horizontal scrollbar.
 * Two things have to hold together for that not to happen: the table must be
 * allowed to lay out in the width it has, and it must stop asking for fourteen
 * columns' worth of it.
 */
test('the issue master table is allowed to fit the screen', () => {
  const html = read('public/backoffice/index.html');
  const css = read('public/backoffice/style.css');
  const js = read('public/backoffice/app.js');

  assert.match(html, /<table id="issueTbl" class="fit">/,
    'the issue table opts out of min-width:max-content');
  assert.match(css, /\.wrap table\.fit\{min-width:0/,
    '.fit is what lets it shrink — without the rule the class does nothing');
  assert.match(css, /\.win\.to::before\{content:'→ '/, 'stacked window ends keep their arrow');

  // The header row it renders, counted. Nine columns fit; fourteen did not.
  const head = js.slice(js.indexOf("pagedTable('issues', $('#issueTbl')"));
  const thead = head.slice(head.indexOf('<thead>'), head.indexOf('</tr></thead>'));
  const cols = (thead.match(/<th[ >]/g) || []).length;   // <thead> itself starts with <th
  assert.ok(cols <= 9, `issue table renders ${cols} columns; keep it at 9 or fewer`);

  // What the columns dropped has to stay reachable, not just disappear.
  assert.match(js, /function issueTermsHtml\(d\)/);
  assert.match(js, /issueSummaryHtml\(d\) \+ issueTermsHtml\(d\)/,
    'the expander shows the terms the table no longer prints');
  for (const k of ['ISIN', 'Tick', 'Lot', 'Retail cut-off min', 'Cut-off bids']) {
    assert.ok(js.slice(js.indexOf('function issueTermsHtml')).slice(0, 2600).includes(k),
      `${k} moved out of the table and must appear in the expander`);
  }
});


/**
 * No internal system names in anything a user reads.
 *
 * "No LD client found for that UCC" told a desk nothing it could act on and sent an
 * AP looking for a system they have never heard of. The names of the upstream
 * databases, schemas and tables are ours; the sentence on the screen has to be about
 * what the person can do next.
 */
test('user-facing strings name no internal system', () => {
  const INTERNAL = [
    [/\bLD\b/, 'LD'], [/\bAnanta\b/i, 'Ananta'], [/branchho/i, 'branchho'],
    [/ask_clientmast/i, 'ask_clientmast'], [/uat_ananta/i, 'uat_ananta'],
    [/admin-staging-api/i, 'admin-staging-api'], [/\bdwh\b/i, 'dwh'],
    [/\bstg\b/i, 'stg'], [/omnenest/i, 'omnenest']
  ];
  // Front-end files only: these are the strings a person actually sees. Comments
  // are stripped first — the code is allowed to say where its data comes from.
  for (const f of ['public/backoffice/app.js', 'public/client/client.js']) {
    const src = read(f)
      .replace(/\/\*[\s\S]*?\*\//g, '')
      .split('\n').filter((l) => !/^\s*\/\//.test(l)).join('\n');
    // Every single- or double-quoted literal that reaches the page.
    const strings = (src.match(/'(?:[^'\\\n]|\\.)*'/g) || []).join('\n');
    for (const [re, name] of INTERNAL) {
      assert.ok(!re.test(strings), f + ' shows the user an internal name: ' + name);
    }
  }
});
