'use strict';
/**
 * The stylesheets and scripts the browser actually loads.
 *
 * This exists because public/backoffice/style.css was once truncated from 24 KB to
 * 815 bytes by a bad append and nothing noticed: every unit test passed, the server
 * started, the page returned 200, and the only symptom was that the back office
 * rendered as unstyled text. A file that is quietly emptied is invisible to every
 * other kind of test here, so it gets its own.
 *
 * The floors are deliberately well under current size — this is a truncation alarm,
 * not a budget. The markers are load-bearing selectors: if one disappears, either
 * the file was clobbered or the class was renamed without updating the HTML.
 */
const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');

const ASSETS = [
  { file: 'public/shared/theme.css',      min: 6000, markers: ['.tabs', '.btn', ':root'] },
  { file: 'public/backoffice/style.css',  min: 15000, markers: ['.pane', '.cards', '.no-grant', '.f .fh'] },
  { file: 'public/backoffice/login.css',  min: 1500, markers: ['.btn-o'] },
  { file: 'public/client/style.css',      min: 6000, markers: ['.issue', '.bidbox', '.bb-row'] },
  { file: 'public/shared/rules.css',      min: 1000, markers: ['.rules'] },
  { file: 'public/backoffice/app.js',     min: 40000, markers: ['function boot(', 'function applyGrants('] },
  { file: 'public/client/client.js',      min: 12000, markers: ['function boot(', 'function bidBox('] },
  { file: 'public/shared/rules.js',       min: 3000, markers: [] }
];

for (const a of ASSETS) {
  test(a.file + ' is present and not truncated', () => {
    const s = read(a.file);
    assert.ok(s.length >= a.min,
      a.file + ' is ' + s.length + ' bytes, under the ' + a.min + ' floor — truncated?');
    for (const m of a.markers) {
      assert.ok(s.includes(m), a.file + ' no longer contains ' + JSON.stringify(m));
    }
  });
}

test('every stylesheet has balanced braces', () => {
  for (const a of ASSETS.filter((x) => x.file.endsWith('.css'))) {
    const s = read(a.file);
    const open = (s.match(/{/g) || []).length;
    const close = (s.match(/}/g) || []).length;
    assert.equal(open, close, a.file + ' has ' + open + ' { and ' + close + ' }');
  }
});

/**
 * Every stylesheet and script the pages reference must exist on disk, resolved the
 * way the server actually mounts them (server.js). The client app is served from
 * '/', so its own '/style.css' is public/client/style.css — not public/style.css,
 * which is what makes this worth checking rather than eyeballing.
 */
const MOUNTS = [
  ['/shared/', 'public/shared/'],
  ['/backoffice/', 'public/backoffice/'],
  ['/', 'public/client/']            // catch-all, so it must come last
];

function resolveRef(url) {
  for (const [prefix, dir] of MOUNTS) {
    if (url.startsWith(prefix)) return dir + url.slice(prefix.length);
  }
  return null;
}

test('every asset each page links actually exists', () => {
  for (const page of ['public/backoffice/index.html', 'public/backoffice/login.html',
                      'public/backoffice/issue.html', 'public/client/index.html']) {
    const html = read(page);
    const refs = [];
    const re = /(?:href|src)="(\/[^"]+\.(?:css|js))"/g;
    let m;
    while ((m = re.exec(html))) refs.push(m[1]);
    assert.ok(refs.length, page + ' links no stylesheet or script at all');
    for (const r of refs) {
      if (r === '/config.js') continue;          // generated by the server, not a file
      const onDisk = resolveRef(r);
      assert.ok(onDisk, page + ' links ' + r + ', which no static mount serves');
      assert.ok(fs.existsSync(path.join(ROOT, onDisk)),
        page + ' links ' + r + ' -> ' + onDisk + ', which does not exist');
    }
  }
});
